---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-generator
  labels:
    app: topology-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-generator
  template:
    metadata:
      labels:
        app: topology-generator
    spec:
      containers:
      - name: topology-generator
        image: quay.io/leandroberetta/topogen:v0.0.1
        imagePullPolicy: Always
        args: ["server"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: topology-generator
spec:
  selector:
    app: topology-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---